session_name: Clustered
windows:
  - window_name: Clustered
    layout: main-vertical
    options:
      main-pane-width: 20%
    panes:
      - shell_command:
          - cd ~/Documents/Notes/Projects/clustered
          # - nvim Notes.md ToDo.md
          - open-project
      - shell_command:
          - tmux resizep -y 85%
          - filelist-open "startup_files.txt" clustered
        focus: true
      - clear
